### ISSUE TITLE
Ability to convert openWakeWord models to microWakeWord?

### ISSUE THREAD

**Issue by sammcj** [kahrendt/microWakeWord#13]
Is there any way to convert openWakeWord models to microWakeWord?

I've been trying to use the provided notebooks to generate `hey_ollama` but haven't had any success so was wondering if I could convert my existing models? (attached for reference).

[hey_ollama.zip](https://github.com/kahrendt/microWakeWord/files/14476003/hey_ollama.zip)

**Comment by synesthesiam** [comment]
No, the models use different architectures entirely. openWakeWord is based on a Google embedding model, while microWakeWord uses something called Inception.

**Comment by sammcj** [comment]
Ah, I see, thanks for letting me know!
