### ISSUE TITLE
Request: Possible to get Hey_mycroft as a wake word ?

### ISSUE THREAD

**Issue by cooljimy84** [kahrendt/microWakeWord#17]
As above, would be nice to get Hey_mycroft as a wake word.

**Comment by kahrendt** [comment]
This is actually the wake word I am currently working on. I had some success generating a model that predicts the TTS samples very well, but it unfortunately did not work well at all in real world testing. I'm exploring why that is happening (especially since I haven't encountered this behavior with the previous models), but hopefully I'll have a model ready in the near future!

**Comment by cooljimy84** [comment]
Kool, I would try running this myself from the colab/Jupiter notepad I found on the archived version, but I suspect me figuring out all the little bits combined with my 3050 would take a few months.

**Comment by sun-xiangyu** [comment]
Hi @cooljimy84 ,

There is a Mycroft wake word in [esp-sr](https://github.com/espressif/esp-sr).  you can try it to see if it meets your requirements.

**Comment by kahrendt** [comment]
I have added a beta version of "Hey Mycroft" model [here]( https://github.com/kahrendt/microWakeWord/releases/tag/hey_mycroft)
Please give it a try and let me know how it works for you! 

I will close this issue once I finish documenting it.

**Comment by andreasbrett** [comment]
> I have added a beta version of "Hey Mycroft" model [here](https://github.com/kahrendt/microWakeWord/releases/tag/hey_mycroft) Please give it a try and let me know how it works for you!
> 
> I will close this issue once I finish documenting it.

How can we reference this model in the esphome microwakeword config?

**Comment by kahrendt** [comment]
> How can we reference this model in the esphome microwakeword config?

Try this under the ``micro_wake_word`` config:
```
  model: https://github.com/kahrendt/microWakeWord/releases/download/hey_mycroft/hey_mycroft.json
```

**Comment by andreasbrett** [comment]
That didn't work unfortunately. Any reason why you post this as a tagged release instead of putting the files in the models folder in a separate branch? Referencing a file in a branch is officially supported in the microwakeword config.
----------------------------------------

May 12, 2024 12:18:14 Kevin Ahrendt - notifications at github.com[https://github.com] ***@***.***>:

**Comment by kahrendt** [comment]
> That didn't work unfortunately. Any reason why you post this as a tagged release instead of putting the files in the models folder in a separate branch? Referencing a file in a branch is officially supported in the microwakeword config.

I've been thinking of moving completed models out of the repo and into the releases section to better handle newer models, so I was experimenting with it. The ESPHome config should also handle a url to a json manifest file. I did however forget that this model uses a new TensorFlow op, and the current code in ESPHome doesn't support it. Sorry about that! I pushed a change to my work in progress PR to add the missing op. I've successfully tested it using the following yaml config:

```
external_components:
  - source: github://pr#6653
    components: [micro_wake_word]
    refresh: 0s

micro_wake_word:
  on_wake_word_detected:
    - voice_assistant.start: 
        wake_word: !lambda return wake_word;
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/hey_mycroft/hey_mycroft.json
```

**Comment by andreasbrett** [comment]
Works great. Very quick recognition in the few tests I could run so far. Even whispering "hey mycroft" while having a TV running in the background worked out well. Also no issues with my german accent. For "hey jarvis" I sometimes had to intentionally pronounce it with american accent to get it to trigger. Once I got the hang though and internalised the pronounciation it was fine. With "hey mycroft" I had no missed wakeword so far.

**Comment by kahrendt** [comment]
Since the "Hey Mycroft" version has been avalaible for use in ESPHome, I'm going to close this.
