### ISSUE TITLE
how to infer the streaming

### ISSUE THREAD

**Issue by kismeter** [kahrendt/microWakeWord#21]
trying to infer whole "Alexa.wav" audio to alexa.tflite using predict_clip, it can be detected the keyword. but when using streaming audio (get 480 samples from "Alexa.wav" with 320 steps) predict_clip result show keyword not detected.
for example:
```
    file_path = "Alexa.wav"
    file_data = tf.io.read_file(file_path)
    samples, sample_rate = tf.audio.decode_wav(file_data, desired_channels=1)
    
    samples = tf.reshape(samples, [-1])
    
    max_value = tf.dtypes.int16.max  # 32767
    min_value = tf.dtypes.int16.min  # -32768
    samples = tf.multiply(samples, -min_value)
    samples = tf.cast(samples, tf.int16)
    
    window_size = 480  # 30ms 
    step_size = 320    # 20ms 
    
    for i in range(0, len(samples) - window_size + 1, step_size):
        chunk = samples[i:i + window_size]
        
        chunk = tf.reshape(chunk, [1, -1])
        
        predictions = kwsModel.predict_clip(chunk.numpy())

        print("Predictions for chunk:", predictions)
```

**Comment by kahrendt** [comment]
The ``predict_clip`` function expects the entire clip to be given at once. It uses TensorFlow's microfrontend Python op to generate the spectrogram features, and that op requires the entire clip at once (it has auto gain control and noise reduction, which requires memory of previous audio windows).

If you want to manually stride the audio window like in your code, you need to use a different feature generation approach. The easiest way is to use the ``tflite_micro`` runtime with the preprocessor model. [This notebook from alior101's repo](https://github.com/alior101/Custom-MicroWakeWord-Generator/blob/main/04_testing_notebook.ipynb) has a great example showing how to do this.

**Comment by kismeter** [comment]
so the streaming infer must use tflite_micro runtime with preprocessor model?

**Comment by kahrendt** [comment]
Yes, that is the most straightforward way to generate the spectrogram features for streaming audio. I haven't personally experimented with it as the ``tflite_micro`` runtime doesn't run on my Mac's M1 processor, but alior101 has had success with that approach.

**Comment by kismeter** [comment]
also not working on Mac's M2. Thanks @kahrendt
