### ISSUE TITLE
Request: Computer wake word

### ISSUE THREAD

**Issue by thexperiments** [kahrendt/microWakeWord#24]
Would be great to have the computer wake word as this is what I have set my Echos to to slowly get away from Amazon.

Would also support training it if you can give some pointers. I don't see how I would create the spectrographs and the training data that is referenced in the readme.md

**Comment by mayorgergich** [comment]
Being able to set custom wake words using MWW would be incredible. Personally we call ours Broccoli.

**Comment by kahrendt** [comment]
Please try out the new training script under notebooks! The initial wake word in that notebook trains a model for "computer"
