### ISSUE TITLE
Before I ask for my own wake word and dozens of other ppl, too...

### ISSUE THREAD

**Issue by dreimer1986** [kahrendt/microWakeWord#27]
Would it be possible to create something like this: https://www.home-assistant.io/voice_control/create_wake_word/ aka this https://colab.research.google.com/drive/1q1oe2zOyZp7UsB3jJiQ1IFn8z5YfjwEb?usp=sharing#scrollTo=1cbqBebHXjFD for microWakeWord, too?

I use "Hey Luna" for wake word for example and there are very likely dozens of other ideas out there and I perfer not to go on your nerves with my special wishes tbh ^^

**Comment by kahrendt** [comment]
That is the eventual goal! You can track the progress in #2. There is still a decent amount of things to be done, but I am slowly getting things in place to make this easier.
