### ISSUE TITLE
[REQUEST] Add both 'Okay Assist' and 'Hey Assist' included as microWakeWord models?

### ISSUE THREAD

**Issue by Hedda** [kahrendt/microWakeWord#32]
Please consider including microWakeWord models for "**_Okay Assist_**" and "**_Hey Assist_**" as combination phrases for "Assist", adding:

- _**Okay Assist.**_

and 

- _**Hey Assist.**_

As in

- "_**Okay Assist, turn on the dining room lights**_", and - "_**Hey Assist, turn off the kitchen lights**_", 

Note that with "Assist" I am referring to Home Assistant's official "Assist" conversation agent in Home Assistant:

* https://www.home-assistant.io/voice_control/

Referring to same virtual assistant used for the integration that is now called "Assist Satellite";

* https://www.home-assistant.io/integrations/assist_satellite/

and is used by the the new "Assist Satellite" entity

* https://developers.home-assistant.io/blog/2024/10/01/assist-satellite-entity/
  * https://developers.home-assistant.io/docs/core/entity/assist-satellite/
    * https://github.com/home-assistant/architecture/discussions/1136
      * https://github.com/home-assistant/core/pulls?q=is%3A+assist_satellite%22

After all, Home Assistant's official voice assistant is called "Assist", and there are even official logos and branding for that name.

![image](https://github.com/user-attachments/assets/6d9cfa1c-cbeb-48d1-b6bb-88bb53377dfd)

PS: Even on Nabu Casa's website it says that "Assist" is official name for the voice assistant, so makes sense "Nabu" including it, or?

* https://www.nabucasa.com/config/assist/

**Comment by kahrendt** [comment]
I have no plans to train these particular wake words (or any other particular wake words) at this point. I will try to build a training script put together for experimenting with creating new wake words, so anyone can use whatever phrase they want.
