### ISSUE TITLE
[REQUEST] Add 'Home Assistant', 'Okay Home Assistant', and 'Hey Home Assistant' as three additional microWakeWord models?

### ISSUE THREAD

**Issue by Hedda** [kahrendt/microWakeWord#33]
Please consider adding 'Home Assistant', 'Okay Home Assistant', and 'Hey Home Assistant' as three additional microWakeWord models?

As is only:

- "_**Home Assistant**_". 

As in

- "_**Home Assistant, turn on the dining room lights**_", and - "_**Home Assistant, turn off the kitchen lights**_", 

or in combinations like:

- "_**Okay Home Assistant**_".

and

- "_**Hey Home Assistant**_".

Would be great with option to set simply 'Home Assistant' as wake word as a way to show off and market for brand recognition.

PS: Wording is unique enough + "Home Assistant" is 4 syllables where "Hey Jarvis", "Hey Siri", and "Alexa" are all only 3 syllables.

**Comment by kahrendt** [comment]
I have no plans to train these particular wake words (or any other particular wake words) at this point. I will try to build a training script put together for experimenting with creating new wake words, so anyone can use whatever phrase they want.
