### ISSUE TITLE
Use the tf4micro esp fork not the tensorflow libs?

### ISSUE THREAD

**Issue by StuartIanNaylor** [kahrendt/microWakeWord#49]
https://github.com/espressif/esp-tflite-micro
https://github.com/espressif/esp-nn

Even though it seems the esp-tflite-micro is behind the newly partitioned https://github.com/tensorflow/tflite-micro repo.
I am not sure but unless you link esp-nn you will not use the optimised vector instructions of the S3 

https://github.com/espressif/esp-nn?tab=readme-ov-file#performance

**Comment by kahrendt** [comment]
The microWakeWord implementation in ESPHome uses the Espressif library which automatically imports the ``esp-nn`` code, so we are already taking advantage of the optimized versions that use the vector instructions. Even the regular ESP32 runs the model faster with their assembly versions compared to disabling the ``esp-nn`` optimizations.

**Comment by StuartIanNaylor** [comment]
I was thinking you would have to adapt the code they provide as it seems for specific input tensors, which changes in each model.
I am not sure but think the optimised code might be the model that runs in the s3-box
